### ISSUE TITLE
How to train on a single GPU ?

### ISSUE THREAD

**Issue by ver0z** [fundamentalvision/Deformable-DETR#110]
Can someone explain how to train on a single GPU ? 

I'm using the base to train of DETR, but it is giving and error after executing the line:

`!python main.py --dataset_file custom --data_path /content/coco --output_dir /content/Output --batch_size 2`

The error is as follows

`Not using distributed mode
git:
  sha: 11169a60c33333af00a4849f1808023eba96a931, status: has uncommited changes, branch: main

Namespace(aux_loss=True, backbone='resnet50', batch_size=2, bbox_loss_coef=5, cache_mode=False, clip_max_norm=0.1, cls_loss_coef=2, coco_panoptic_path=None, data_path='/content/coco', dataset_file='custom', dec_layers=6, dec_n_points=4, device='cuda', dice_loss_coef=1, dilation=False, dim_feedforward=1024, distributed=False, dropout=0.1, enc_layers=6, enc_n_points=4, epochs=50, eval=False, focal_alpha=0.25, frozen_weights=None, giou_loss_coef=2, hidden_dim=256, lr=0.0002, lr_backbone=2e-05, lr_backbone_names=['backbone.0'], lr_drop=40, lr_drop_epochs=None, lr_linear_proj_mult=0.1, lr_linear_proj_names=['reference_points', 'sampling_offsets'], mask_loss_coef=1, masks=False, nheads=8, num_feature_levels=4, num_queries=300, num_workers=2, output_dir='/content/Output', position_embedding='sine', position_embedding_scale=6.283185307179586, remove_difficult=False, resume='', seed=42, set_cost_bbox=5, set_cost_class=2, set_cost_giou=2, sgd=False, start_epoch=0, two_stage=False, weight_decay=0.0001, with_box_refine=False)
number of params: 39824906
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
transformer.level_embed
transformer.encoder.layers.0.self_attn.sampling_offsets.weight
transformer.encoder.layers.0.self_attn.sampling_offsets.bias
transformer.encoder.layers.0.self_attn.attention_weights.weight
transformer.encoder.layers.0.self_attn.attention_weights.bias
transformer.encoder.layers.0.self_attn.value_proj.weight
transformer.encoder.layers.0.self_attn.value_proj.bias
transformer.encoder.layers.0.self_attn.output_proj.weight
transformer.encoder.layers.0.self_attn.output_proj.bias
transformer.encoder.layers.0.norm1.weight
transformer.encoder.layers.0.norm1.bias
transformer.encoder.layers.0.linear1.weight
transformer.encoder.layers.0.linear1.bias
transformer.encoder.layers.0.linear2.weight
transformer.encoder.layers.0.linear2.bias
transformer.encoder.layers.0.norm2.weight
transformer.encoder.layers.0.norm2.bias
transformer.encoder.layers.1.self_attn.sampling_offsets.weight
transformer.encoder.layers.1.self_attn.sampling_offsets.bias
transformer.encoder.layers.1.self_attn.attention_weights.weight
transformer.encoder.layers.1.self_attn.attention_weights.bias
transformer.encoder.layers.1.self_attn.value_proj.weight
transformer.encoder.layers.1.self_attn.value_proj.bias
transformer.encoder.layers.1.self_attn.output_proj.weight
transformer.encoder.layers.1.self_attn.output_proj.bias
transformer.encoder.layers.1.norm1.weight
transformer.encoder.layers.1.norm1.bias
transformer.encoder.layers.1.linear1.weight
transformer.encoder.layers.1.linear1.bias
transformer.encoder.layers.1.linear2.weight
transformer.encoder.layers.1.linear2.bias
transformer.encoder.layers.1.norm2.weight
transformer.encoder.layers.1.norm2.bias
transformer.encoder.layers.2.self_attn.sampling_offsets.weight
transformer.encoder.layers.2.self_attn.sampling_offsets.bias
transformer.encoder.layers.2.self_attn.attention_weights.weight
transformer.encoder.layers.2.self_attn.attention_weights.bias
transformer.encoder.layers.2.self_attn.value_proj.weight
transformer.encoder.layers.2.self_attn.value_proj.bias
transformer.encoder.layers.2.self_attn.output_proj.weight
transformer.encoder.layers.2.self_attn.output_proj.bias
transformer.encoder.layers.2.norm1.weight
transformer.encoder.layers.2.norm1.bias
transformer.encoder.layers.2.linear1.weight
transformer.encoder.layers.2.linear1.bias
transformer.encoder.layers.2.linear2.weight
transformer.encoder.layers.2.linear2.bias
transformer.encoder.layers.2.norm2.weight
transformer.encoder.layers.2.norm2.bias
transformer.encoder.layers.3.self_attn.sampling_offsets.weight
transformer.encoder.layers.3.self_attn.sampling_offsets.bias
transformer.encoder.layers.3.self_attn.attention_weights.weight
transformer.encoder.layers.3.self_attn.attention_weights.bias
transformer.encoder.layers.3.self_attn.value_proj.weight
transformer.encoder.layers.3.self_attn.value_proj.bias
transformer.encoder.layers.3.self_attn.output_proj.weight
transformer.encoder.layers.3.self_attn.output_proj.bias
transformer.encoder.layers.3.norm1.weight
transformer.encoder.layers.3.norm1.bias
transformer.encoder.layers.3.linear1.weight
transformer.encoder.layers.3.linear1.bias
transformer.encoder.layers.3.linear2.weight
transformer.encoder.layers.3.linear2.bias
transformer.encoder.layers.3.norm2.weight
transformer.encoder.layers.3.norm2.bias
transformer.encoder.layers.4.self_attn.sampling_offsets.weight
transformer.encoder.layers.4.self_attn.sampling_offsets.bias
transformer.encoder.layers.4.self_attn.attention_weights.weight
transformer.encoder.layers.4.self_attn.attention_weights.bias
transformer.encoder.layers.4.self_attn.value_proj.weight
transformer.encoder.layers.4.self_attn.value_proj.bias
transformer.encoder.layers.4.self_attn.output_proj.weight
transformer.encoder.layers.4.self_attn.output_proj.bias
transformer.encoder.layers.4.norm1.weight
transformer.encoder.layers.4.norm1.bias
transformer.encoder.layers.4.linear1.weight
transformer.encoder.layers.4.linear1.bias
transformer.encoder.layers.4.linear2.weight
transformer.encoder.layers.4.linear2.bias
transformer.encoder.layers.4.norm2.weight
transformer.encoder.layers.4.norm2.bias
transformer.encoder.layers.5.self_attn.sampling_offsets.weight
transformer.encoder.layers.5.self_attn.sampling_offsets.bias
transformer.encoder.layers.5.self_attn.attention_weights.weight
transformer.encoder.layers.5.self_attn.attention_weights.bias
transformer.encoder.layers.5.self_attn.value_proj.weight
transformer.encoder.layers.5.self_attn.value_proj.bias
transformer.encoder.layers.5.self_attn.output_proj.weight
transformer.encoder.layers.5.self_attn.output_proj.bias
transformer.encoder.layers.5.norm1.weight
transformer.encoder.layers.5.norm1.bias
transformer.encoder.layers.5.linear1.weight
transformer.encoder.layers.5.linear1.bias
transformer.encoder.layers.5.linear2.weight
transformer.encoder.layers.5.linear2.bias
transformer.encoder.layers.5.norm2.weight
transformer.encoder.layers.5.norm2.bias
transformer.decoder.layers.0.cross_attn.sampling_offsets.weight
transformer.decoder.layers.0.cross_attn.sampling_offsets.bias
transformer.decoder.layers.0.cross_attn.attention_weights.weight
transformer.decoder.layers.0.cross_attn.attention_weights.bias
transformer.decoder.layers.0.cross_attn.value_proj.weight
transformer.decoder.layers.0.cross_attn.value_proj.bias
transformer.decoder.layers.0.cross_attn.output_proj.weight
transformer.decoder.layers.0.cross_attn.output_proj.bias
transformer.decoder.layers.0.norm1.weight
transformer.decoder.layers.0.norm1.bias
transformer.decoder.layers.0.self_attn.in_proj_weight
transformer.decoder.layers.0.self_attn.in_proj_bias
transformer.decoder.layers.0.self_attn.out_proj.weight
transformer.decoder.layers.0.self_attn.out_proj.bias
transformer.decoder.layers.0.norm2.weight
transformer.decoder.layers.0.norm2.bias
transformer.decoder.layers.0.linear1.weight
transformer.decoder.layers.0.linear1.bias
transformer.decoder.layers.0.linear2.weight
transformer.decoder.layers.0.linear2.bias
transformer.decoder.layers.0.norm3.weight
transformer.decoder.layers.0.norm3.bias
transformer.decoder.layers.1.cross_attn.sampling_offsets.weight
transformer.decoder.layers.1.cross_attn.sampling_offsets.bias
transformer.decoder.layers.1.cross_attn.attention_weights.weight
transformer.decoder.layers.1.cross_attn.attention_weights.bias
transformer.decoder.layers.1.cross_attn.value_proj.weight
transformer.decoder.layers.1.cross_attn.value_proj.bias
transformer.decoder.layers.1.cross_attn.output_proj.weight
transformer.decoder.layers.1.cross_attn.output_proj.bias
transformer.decoder.layers.1.norm1.weight
transformer.decoder.layers.1.norm1.bias
transformer.decoder.layers.1.self_attn.in_proj_weight
transformer.decoder.layers.1.self_attn.in_proj_bias
transformer.decoder.layers.1.self_attn.out_proj.weight
transformer.decoder.layers.1.self_attn.out_proj.bias
transformer.decoder.layers.1.norm2.weight
transformer.decoder.layers.1.norm2.bias
transformer.decoder.layers.1.linear1.weight
transformer.decoder.layers.1.linear1.bias
transformer.decoder.layers.1.linear2.weight
transformer.decoder.layers.1.linear2.bias
transformer.decoder.layers.1.norm3.weight
transformer.decoder.layers.1.norm3.bias
transformer.decoder.layers.2.cross_attn.sampling_offsets.weight
transformer.decoder.layers.2.cross_attn.sampling_offsets.bias
transformer.decoder.layers.2.cross_attn.attention_weights.weight
transformer.decoder.layers.2.cross_attn.attention_weights.bias
transformer.decoder.layers.2.cross_attn.value_proj.weight
transformer.decoder.layers.2.cross_attn.value_proj.bias
transformer.decoder.layers.2.cross_attn.output_proj.weight
transformer.decoder.layers.2.cross_attn.output_proj.bias
transformer.decoder.layers.2.norm1.weight
transformer.decoder.layers.2.norm1.bias
transformer.decoder.layers.2.self_attn.in_proj_weight
transformer.decoder.layers.2.self_attn.in_proj_bias
transformer.decoder.layers.2.self_attn.out_proj.weight
transformer.decoder.layers.2.self_attn.out_proj.bias
transformer.decoder.layers.2.norm2.weight
transformer.decoder.layers.2.norm2.bias
transformer.decoder.layers.2.linear1.weight
transformer.decoder.layers.2.linear1.bias
transformer.decoder.layers.2.linear2.weight
transformer.decoder.layers.2.linear2.bias
transformer.decoder.layers.2.norm3.weight
transformer.decoder.layers.2.norm3.bias
transformer.decoder.layers.3.cross_attn.sampling_offsets.weight
transformer.decoder.layers.3.cross_attn.sampling_offsets.bias
transformer.decoder.layers.3.cross_attn.attention_weights.weight
transformer.decoder.layers.3.cross_attn.attention_weights.bias
transformer.decoder.layers.3.cross_attn.value_proj.weight
transformer.decoder.layers.3.cross_attn.value_proj.bias
transformer.decoder.layers.3.cross_attn.output_proj.weight
transformer.decoder.layers.3.cross_attn.output_proj.bias
transformer.decoder.layers.3.norm1.weight
transformer.decoder.layers.3.norm1.bias
transformer.decoder.layers.3.self_attn.in_proj_weight
transformer.decoder.layers.3.self_attn.in_proj_bias
transformer.decoder.layers.3.self_attn.out_proj.weight
transformer.decoder.layers.3.self_attn.out_proj.bias
transformer.decoder.layers.3.norm2.weight
transformer.decoder.layers.3.norm2.bias
transformer.decoder.layers.3.linear1.weight
transformer.decoder.layers.3.linear1.bias
transformer.decoder.layers.3.linear2.weight
transformer.decoder.layers.3.linear2.bias
transformer.decoder.layers.3.norm3.weight
transformer.decoder.layers.3.norm3.bias
transformer.decoder.layers.4.cross_attn.sampling_offsets.weight
transformer.decoder.layers.4.cross_attn.sampling_offsets.bias
transformer.decoder.layers.4.cross_attn.attention_weights.weight
transformer.decoder.layers.4.cross_attn.attention_weights.bias
transformer.decoder.layers.4.cross_attn.value_proj.weight
transformer.decoder.layers.4.cross_attn.value_proj.bias
transformer.decoder.layers.4.cross_attn.output_proj.weight
transformer.decoder.layers.4.cross_attn.output_proj.bias
transformer.decoder.layers.4.norm1.weight
transformer.decoder.layers.4.norm1.bias
transformer.decoder.layers.4.self_attn.in_proj_weight
transformer.decoder.layers.4.self_attn.in_proj_bias
transformer.decoder.layers.4.self_attn.out_proj.weight
transformer.decoder.layers.4.self_attn.out_proj.bias
transformer.decoder.layers.4.norm2.weight
transformer.decoder.layers.4.norm2.bias
transformer.decoder.layers.4.linear1.weight
transformer.decoder.layers.4.linear1.bias
transformer.decoder.layers.4.linear2.weight
transformer.decoder.layers.4.linear2.bias
transformer.decoder.layers.4.norm3.weight
transformer.decoder.layers.4.norm3.bias
transformer.decoder.layers.5.cross_attn.sampling_offsets.weight
transformer.decoder.layers.5.cross_attn.sampling_offsets.bias
transformer.decoder.layers.5.cross_attn.attention_weights.weight
transformer.decoder.layers.5.cross_attn.attention_weights.bias
transformer.decoder.layers.5.cross_attn.value_proj.weight
transformer.decoder.layers.5.cross_attn.value_proj.bias
transformer.decoder.layers.5.cross_attn.output_proj.weight
transformer.decoder.layers.5.cross_attn.output_proj.bias
transformer.decoder.layers.5.norm1.weight
transformer.decoder.layers.5.norm1.bias
transformer.decoder.layers.5.self_attn.in_proj_weight
transformer.decoder.layers.5.self_attn.in_proj_bias
transformer.decoder.layers.5.self_attn.out_proj.weight
transformer.decoder.layers.5.self_attn.out_proj.bias
transformer.decoder.layers.5.norm2.weight
transformer.decoder.layers.5.norm2.bias
transformer.decoder.layers.5.linear1.weight
transformer.decoder.layers.5.linear1.bias
transformer.decoder.layers.5.linear2.weight
transformer.decoder.layers.5.linear2.bias
transformer.decoder.layers.5.norm3.weight
transformer.decoder.layers.5.norm3.bias
transformer.reference_points.weight
transformer.reference_points.bias
class_embed.0.weight
class_embed.0.bias
bbox_embed.0.layers.0.weight
bbox_embed.0.layers.0.bias
bbox_embed.0.layers.1.weight
bbox_embed.0.layers.1.bias
bbox_embed.0.layers.2.weight
bbox_embed.0.layers.2.bias
query_embed.weight
input_proj.0.0.weight
input_proj.0.0.bias
input_proj.0.1.weight
input_proj.0.1.bias
input_proj.1.0.weight
input_proj.1.0.bias
input_proj.1.1.weight
input_proj.1.1.bias
input_proj.2.0.weight
input_proj.2.0.bias
input_proj.2.1.weight
input_proj.2.1.bias
input_proj.3.0.weight
input_proj.3.0.bias
input_proj.3.1.weight
input_proj.3.1.bias
backbone.0.body.conv1.weight
backbone.0.body.layer1.0.conv1.weight
backbone.0.body.layer1.0.conv2.weight
backbone.0.body.layer1.0.conv3.weight
backbone.0.body.layer1.0.downsample.0.weight
backbone.0.body.layer1.1.conv1.weight
backbone.0.body.layer1.1.conv2.weight
backbone.0.body.layer1.1.conv3.weight
backbone.0.body.layer1.2.conv1.weight
backbone.0.body.layer1.2.conv2.weight
backbone.0.body.layer1.2.conv3.weight
backbone.0.body.layer2.0.conv1.weight
backbone.0.body.layer2.0.conv2.weight
backbone.0.body.layer2.0.conv3.weight
backbone.0.body.layer2.0.downsample.0.weight
backbone.0.body.layer2.1.conv1.weight
backbone.0.body.layer2.1.conv2.weight
backbone.0.body.layer2.1.conv3.weight
backbone.0.body.layer2.2.conv1.weight
backbone.0.body.layer2.2.conv2.weight
backbone.0.body.layer2.2.conv3.weight
backbone.0.body.layer2.3.conv1.weight
backbone.0.body.layer2.3.conv2.weight
backbone.0.body.layer2.3.conv3.weight
backbone.0.body.layer3.0.conv1.weight
backbone.0.body.layer3.0.conv2.weight
backbone.0.body.layer3.0.conv3.weight
backbone.0.body.layer3.0.downsample.0.weight
backbone.0.body.layer3.1.conv1.weight
backbone.0.body.layer3.1.conv2.weight
backbone.0.body.layer3.1.conv3.weight
backbone.0.body.layer3.2.conv1.weight
backbone.0.body.layer3.2.conv2.weight
backbone.0.body.layer3.2.conv3.weight
backbone.0.body.layer3.3.conv1.weight
backbone.0.body.layer3.3.conv2.weight
backbone.0.body.layer3.3.conv3.weight
backbone.0.body.layer3.4.conv1.weight
backbone.0.body.layer3.4.conv2.weight
backbone.0.body.layer3.4.conv3.weight
backbone.0.body.layer3.5.conv1.weight
backbone.0.body.layer3.5.conv2.weight
backbone.0.body.layer3.5.conv3.weight
backbone.0.body.layer4.0.conv1.weight
backbone.0.body.layer4.0.conv2.weight
backbone.0.body.layer4.0.conv3.weight
backbone.0.body.layer4.0.downsample.0.weight
backbone.0.body.layer4.1.conv1.weight
backbone.0.body.layer4.1.conv2.weight
backbone.0.body.layer4.1.conv3.weight
backbone.0.body.layer4.2.conv1.weight
backbone.0.body.layer4.2.conv2.weight
backbone.0.body.layer4.2.conv3.weight
Start training
Traceback (most recent call last):
  File "main.py", line 333, in <module>
    main(args)
  File "main.py", line 282, in main
    model, criterion, data_loader_train, optimizer, device, epoch, args.clip_max_norm)
  File "/content/Deformable-DETR1/engine.py", line 43, in train_one_epoch
    loss_dict = criterion(outputs, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/Deformable-DETR1/models/deformable_detr.py", line 342, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/Deformable-DETR1/models/matcher.py", line 88, in forward
    cost_giou = -generalized_box_iou(box_cxcywh_to_xyxy(out_bbox),
  File "/content/Deformable-DETR1/util/box_ops.py", line 19, in box_cxcywh_to_xyxy
    b = [(x_c - 0.5 * w), (y_c - 0.5 * h),
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [3,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [4,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [2,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [43,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [47,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [55,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [7,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [11,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [15,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [1,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fe2de2312f2 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7fe2de22e67b in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7fe2de4891f9 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7fe2de2193a4 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6e9f8a (0x7fe32b009f8a in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6ea031 (0x7fe32b00a031 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #19: __libc_start_main + 0xe7 (0x7fe33c831bf7 in /lib/x86_64-linux-gnu/libc.so.6)`

**Comment by charleneolive** [comment]
Hi, did you manage to try that out?

**Comment by ver0z** [comment]
Yeah, I solved it. I just changed the number of classes and made others modifications, I forked this repository and made some fixes, this version is on my github. I putted some comments to guide how to run for one GPU.

**Comment by charlene-ong-zl** [comment]
awesome, thank you!

**Comment by IISCAditayTripathi** [comment]
@ver0z How long does it take to train on a single GPU? Kindly provide the details of the GPU you used. And what was the batch size that you were able to fit in a GPU ?

**Comment by ver0z** [comment]
@IISCAditayTripathi I used a  NVIDIA Tesla A100-SXM4-40GB for a small dataset of 24k imagens. It could only run with 4 batches and took around 50 minutes by epoch.

**Comment by IISCAditayTripathi** [comment]
were you able to fit only 4 images in a 40 GB GPU?

**Comment by ver0z** [comment]
Yes, the imagens were big

**Comment by IISCAditayTripathi** [comment]
Roughly how big were the images ?

**Comment by weiliangwuw** [comment]
> @IISCAditayTripathi I used a NVIDIA Tesla A100-SXM4-40GB for a small dataset of 24k imagens. It could only run with 4 batches and took around 50 minutes by epoch.

使用你的方案 还是不行

**Comment by weiliangwuw** [comment]
> Yeah, I solved it. I just changed the number of classes and made others modifications, I forked this repository and made some fixes, this version is on my github. I putted some comments to guide how to run for one GPU.

使用你的方案，还是不行
