### ISSUE TITLE
error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by zhijieshen-bjtu** [fundamentalvision/Deformable-DETR#88]

**Comment by HaoZhang534** [comment]
Have you solve this problem? I also meet this.

**Comment by sjtuytc** [comment]
I also met this problem.

**Comment by sjtuytc** [comment]
The training environment is 8 V100. And the training does not stop while this error message keeps popping up.

**Comment by Jarvis73** [comment]
I met this problem with `pytorch=1.6.0` and **cudatoolkit=10.1**. And I solved this problem by downgrading the cuda version to 9.2.

Full solution:
1. Create a new conda environment. Activate this environment.
2. Install pytorch with `conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=9.2 -c pytorch`
3. Install cuda-9.2. It is the complete cudatoolkit with `cuda-9.2/bin/nvcc` for compiling cuda code. (The cudatoolkit in pytorch is not complete, and has no nvcc tool.) I just copy a cuda-9.2 from another place.
4. `cd models/ops`
5. Edit `setup.py`: Add `"/path/to/cuda-9.2/include"` to the list `include_dirs`, such as `include_dirs = [extensions_dir, "/path/to/cuda-9.2/include"]`
6. Compile with `CUDA_HOME="/path/to/cuda-9.2" PATH="/path/to/cuda-9.2/bin:$PATH" LD_LIBRARY_PATH="/path/to/cuda-9.2/lib64/:$LD_LIBRARY_PATH" python setup.py build install`
7. After install,  move the file `build/lib.linux-x86_64-3.7/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so` to the project root directory and then python can find it.

**Comment by sjtuytc** [comment]
I solved this by simply reinstall NumPy and rebuilding the project. The reason is that some cuda version is not consistent and we need a rebuilt.

**Comment by 9p15p** [comment]
> I solved this by simply reinstall NumPy and rebuilding the project. The reason is that some cuda version is not consistent and we need a rebuilt.
Hi, I also met this error. Could you provide the version of your NumPy?  Thank you.

**Comment by 9p15p** [comment]
> I solved this by simply reinstall NumPy and rebuilding the project. The reason is that some cuda version is not consistent and we need a rebuilt.

Hi, I also met this error. Could you provide the version of your NumPy? Thank you.

**Comment by ZXYFrank** [comment]
Hello. I'm using it on Titan Xp, with `conda install pytorch=1.5.1 torchvision=0.6.1 cudatoolkit=9.2 -c pytorch`. The error is as described in the question.

![image](https://user-images.githubusercontent.com/49837632/180606341-924f3671-f02f-44bb-b473-35d58908455c.png)


I just use `conda install pytorch==1.5.1 torchvision==0.6.1 cudatoolkit=10.1 -c pytorch` together with `python setup.py clean --all` :tada: It works!

Maybe it's just because of the incompatible cudatoolkit version, which seems to have no effect on the codes.

**Comment by Geo99pro** [comment]
I solved this problem based on this [discussion](https://discuss.pytorch.org/t/unable-to-run-on-v100/147542).
You should see first what is the arch  version of your gpu and add it to the list of the env var TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0" before the build.

I hope that help.

**Comment by hanxuezzz** [comment]
> The training environment is 8 V100. And the training does not stop while this error message keeps popping up.
Hello, I just met the same problem as yours, I also run it on a V100 cloud server. Have you solved this problem?

**Comment by hanxuezzz** [comment]
> I solved this by simply reinstall NumPy and rebuilding the project. The reason is that some cuda version is not consistent and we need a rebuilt.

hello，I met this problem too. Could you please tell me what Numpy version you use?

**Comment by hanxuezzz** [comment]
> > I solved this by simply reinstall NumPy and rebuilding the project. The reason is that some cuda version is not consistent and we need a rebuilt.
> 
> Hi, I also met this error. Could you provide the version of your NumPy? Thank you.

Hi, have you solve this problem? I met the same problem too and I can't solve it.

**Comment by lix19937** [comment]
I don’t know how you’ve installed of built it but based on the error message the CUDA kernel was not built for your GPU architecture (sm_86) so you might need to rebuild it for this arch or install the right binary.

**Comment by mrghofrani** [comment]
In my case with GroundingDino, I had to rebuild it using `pip install -e .` to resolve the issue.
